name: cade_meu_pet
description: Projeto da disciplina de Tópicos Especiais.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  carousel_slider: ^4.2.0
  font_awesome_flutter: ^10.3.0
  hasura_connect: ^4.0.0+4
  dio: ^4.0.6
  diacritic: ^0.1.3
  string_validator: ^0.3.0
  intl: ^0.18.0
  share_plus: ^4.0.7
  path_provider: ^2.0.11
  cached_network_image: ^3.2.0
  lottie: ^1.3.0
  flutter_launcher_icons: ^0.11.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/app/ui/assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:

    - lib/app/ui/assets/images/ 
    - lib/app/ui/assets/lottie/ 

